{% set name = "flask-session" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/F/Flask-Session/flask_session-0.8.0.tar.gz
  sha256: 20e045eb01103694e70be4a49f3a80dbb1b57296a22dc6f44bbf3f83ef0742ff

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - flit-core <4
  run:
    - python
    - cachelib
    - flask >=2.2
    - msgspec >=0.18.6
  run_constrained:
    - cachelib >=0.10.2
    - pymongo >=4.6.2
    - redis-py >=5.0.3
    - flask-sqlalchemy >=3.0.5

test:
  requires:
    - pip
  imports:
    - flask_session
  commands:
    - pip check

about:
  home: https://github.com/fengsp/flask-session
  summary: Adds server-side session support to your Flask application
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
